// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProsysWork.Data;

#nullable disable

namespace ProsysWork.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119190428_RemoveIdentityFromShagirdNomresi")]
    partial class RemoveIdentityFromShagirdNomresi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProsysWork.Models.Ders", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MuellimAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MuellimSoyadi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("Sinifi")
                        .HasColumnType("smallint");

                    b.HasKey("DersKodu");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("ProsysWork.Models.Imtahan", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<int>("ShagirdNomresi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImtahanTarixi")
                        .HasColumnType("date");

                    b.Property<byte>("Qiymeti")
                        .HasColumnType("tinyint");

                    b.HasKey("DersKodu", "ShagirdNomresi", "ImtahanTarixi");

                    b.HasIndex("ShagirdNomresi");

                    b.ToTable("Imtahanlar");
                });

            modelBuilder.Entity("ProsysWork.Models.Shagird", b =>
                {
                    b.Property<int>("Nomresi")
                        .HasColumnType("int");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<short>("Sinifi")
                        .HasColumnType("smallint");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Nomresi");

                    b.ToTable("Shagirdler");
                });

            modelBuilder.Entity("ProsysWork.Models.Imtahan", b =>
                {
                    b.HasOne("ProsysWork.Models.Ders", "Ders")
                        .WithMany("Imtahanlar")
                        .HasForeignKey("DersKodu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsysWork.Models.Shagird", "Shagird")
                        .WithMany("Imtahanlar")
                        .HasForeignKey("ShagirdNomresi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Shagird");
                });

            modelBuilder.Entity("ProsysWork.Models.Ders", b =>
                {
                    b.Navigation("Imtahanlar");
                });

            modelBuilder.Entity("ProsysWork.Models.Shagird", b =>
                {
                    b.Navigation("Imtahanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
